"""them truong avatar cho user va image cho coures

Revision ID: 128244e3e481
Revises: d77074dc7a64
Create Date: 2025-07-07 15:44:50.543862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128244e3e481'
down_revision = 'd77074dc7a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=225), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
