"""cập nhật 1 số quan hệ

Revision ID: 2fdc0321f271
Revises: dfafd5402457
Create Date: 2025-07-09 20:36:21.619294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fdc0321f271'
down_revision = 'dfafd5402457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chapter_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('course_review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('course_review_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('course_review_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('enrollment_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('enrollment_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lesson_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chapter', ['chapter_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lesson_comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lesson_comment_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('lesson_comment_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lesson', ['lesson_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lesson_progress_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('lesson_progress_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lesson', ['lesson_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lesson_progress_ibfk_2'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('lesson_progress_ibfk_1'), 'lesson', ['lesson_id'], ['id'])

    with op.batch_alter_table('lesson_comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lesson_comment_ibfk_3'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('lesson_comment_ibfk_1'), 'lesson', ['lesson_id'], ['id'])

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lesson_ibfk_1'), 'chapter', ['chapter_id'], ['id'])

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('enrollment_ibfk_2'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('enrollment_ibfk_1'), 'course', ['course_id'], ['id'])

    with op.batch_alter_table('course_review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('course_review_ibfk_1'), 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('course_review_ibfk_2'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chapter_ibfk_1'), 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###
