"""change user_id in LessonComment to user

Revision ID: 5ef7eb9d5649
Revises: 5797efee80e5
Create Date: 2025-07-21 20:37:29.615262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ef7eb9d5649'
down_revision = '5797efee80e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lesson_comment_ibfk_3'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('lesson_comment_ibfk_3'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
