"""empty message

Revision ID: aefb7aac70a4
Revises: 2fdc0321f271
Create Date: 2025-07-11 20:14:05.135725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aefb7aac70a4'
down_revision = '2fdc0321f271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_comment', schema=None) as batch_op:
        batch_op.drop_column('is_locked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
